### ISSUE TITLE
001 -Diseño de mockups de interfaz básica

### ISSUE THREAD

**Issue by mrf1989** [egc-guadalentin/decide#15]

**Comment by mrf1989** [comment]
Mockup propuesto por @jorandmol 

![mockup-01](https://user-images.githubusercontent.com/18377908/101766492-2785cf00-3ae3-11eb-835c-8dae96295d68.jpg)

**Comment by mrf1989** [comment]
Hemos estado investigando el código base y hemos visto que utilizan [BootstrapVue](https://bootstrap-vue.org/), que está pensado para [aplicaciones accesibles](https://developer.mozilla.org/es/docs/Web/Accessibility/ARIA), por lo que es un buen punto de partida para darle forma a las ideas que tenemos planteadas para cabina de votación.

Cuando los compañeros faciliten más documentación sobre accesibilidad podremos profundizar más en solución.

Por lo pronto estaría bien documentarse sobre todas estas tecnologías y reformular algún que otro mockup.

**Comment by jorandmol** [comment]
Adjunto otra posible configuración de la interfaz gráfica propuesta por @mrf1989 en nuestra reunión. Entre los integrantes del grupo decidiremos cuál es la elegida. 
![photo_2020-12-11_12-21-37](https://user-images.githubusercontent.com/56023983/101897849-7bf48180-3bab-11eb-9e08-106a3684c297.jpg)
