### ISSUE TITLE
Soporte a las pruebas (usabilidad)

### ISSUE THREAD

**Issue by Seelenfur** [egc-guadalentin/decide#450]
**Descripción del problema**
No hay test de carga.

**Especificación del problema**
No procede, propuesta de mejora.

**Necesidades del subsistema**
No procede, propuesta de mejora.

**Propuestas de mejora**
Se propone añadir a los test ya creados alguno de tipo carga para tener más variedad de pruebas.

**Comment by sersanleo** [comment]
Los ha hecho @marfergon23
